### ISSUE TITLE
Ajout du mode d'emploi (enhancement)

### ISSUE THREAD

**Issue by Pinkilla** [christophercrouzet/dotclear-plugins-postsStats#12]
Salut,

Ce serait plus facile si tu ajoutais le mode d'emploi contenu dans le readme dans ta page index histoire de l'avoir sous les yeux à partir de l'admin de dotclear. 

Merci

**Comment by christophercrouzet** [comment]
Je crois qu'il est temps de tourner la page sur cette issue ! :)
